//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio_Medico_Ana.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int Id_Citas { get; set; }
        public Nullable<System.DateTime> Fecha_Cita { get; set; }
        public string Hora_Cita { get; set; }
        public Nullable<int> Id_Paciente { get; set; }
        public Nullable<int> Id_Medico { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
        public string Usuario_Registro { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
