//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio_Medico_Ana.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        public Medico()
        {
            this.Citas = new HashSet<Cita>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int Id_Medico { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Direccion { get; set; }
        public string Jornada { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Telefono_Oficina { get; set; }
    
        public virtual ICollection<Cita> Citas { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
