//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio_Medico_Ana.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.Citas = new HashSet<Cita>();
        }
    
        public int Id_Paciente { get; set; }
        public string Carnet { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
    
        public virtual ICollection<Cita> Citas { get; set; }
    }
}
